name: pa11y
on:
  workflow_dispatch:

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run pa11y
        run: |
          npx pa11y-ci --config pa11y-config.json --threshold 1000
      - name: Commit and push changed files
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "pa11y-report: ${timestamp}" || exit 0
          git push
